name: Titanic MLOps Pipeline

on:
  push:
    branches: [ dev ]

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Pull data with DVC
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: dvc pull

      - name: Train and log to MLflow
        run: python train.py

      - name: Upload model_info.txt
        uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: model_info.txt

      - name: Upload mlruns
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download model_info.txt
        uses: actions/download-artifact@v4
        with:
          name: model-info

      - name: Download mlruns
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: mlruns

      - name: Check accuracy threshold
        run: python check_threshold.py

      - name: Mock Docker build
        run: echo "Building Docker image for Run ID $(cat model_info.txt)"